import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CartService } from '../core/cart.service';
import { I18nService } from '../core/i18n.service';
import { money } from '../core/format';

@Component({ imports:[RouterLink], changeDetection:ChangeDetectionStrategy.OnPush, template:`
  <section class="shell py-14"><p class="eyebrow text-rust">{{i18n.t('cart.eyebrow')}}</p><h1 class="mt-3 font-display text-6xl font-bold">{{i18n.t('cart.title')}}</h1>
  @if(!cart.lines().length){<div class="panel mt-10 p-10 text-center"><p class="font-display text-3xl">{{i18n.t('cart.empty')}}</p><a routerLink="/shop" class="btn btn-primary mt-6">{{i18n.t('cart.continue')}}</a></div>}@else{
    <div class="mt-10 grid items-start gap-8 lg:grid-cols-[1fr_22rem]"><div class="overflow-hidden rounded-2xl border border-ink/10 bg-paper">@for(line of cart.lines();track line.item.uuid){<article class="grid grid-cols-[5rem_1fr] gap-5 border-b border-ink/10 p-5 last:border-0 sm:grid-cols-[7rem_1fr_auto]">
      <div class="aspect-square overflow-hidden rounded-xl bg-sand/30">@if(line.item.media.main_image){<img [src]="line.item.media.main_image" [alt]="line.item.name" class="h-full w-full object-cover">}</div><div><a [routerLink]="['/shop',line.item.uuid]" class="font-display text-xl font-bold">{{line.item.name}}</a><p class="mt-1 text-sm text-ink/55">{{line.item.sku}}</p><div class="mt-4 flex items-center gap-2"><button class="h-8 w-8 rounded-full border border-ink/20" (click)="cart.quantity(line.item.uuid,line.quantity-1)">−</button><span class="min-w-6 text-center">{{line.quantity}}</span><button class="h-8 w-8 rounded-full border border-ink/20" (click)="cart.quantity(line.item.uuid,line.quantity+1)">+</button><button class="ml-3 text-sm text-rust" (click)="cart.remove(line.item.uuid)">{{i18n.t('cart.remove')}}</button></div></div><strong class="col-start-2 sm:col-auto">{{lineTotal(line.item.price.amount,line.quantity,line.item.price.currency)}}</strong>
    </article>}</div><aside class="panel p-6 lg:sticky lg:top-24"><h2 class="font-display text-2xl font-bold">{{i18n.t('checkout.summary')}}</h2><div class="mt-6 flex justify-between border-t border-ink/15 pt-5"><span>{{i18n.t('cart.total')}}</span><strong class="text-xl">{{total()}}</strong></div><p class="mt-2 text-xs leading-5 text-ink/50">{{i18n.t('cart.taxNote')}}</p><a routerLink="/checkout" class="btn btn-primary mt-6 w-full">{{i18n.t('cart.checkout')}}</a><a routerLink="/shop" class="mt-4 block text-center text-sm font-bold">{{i18n.t('cart.continue')}}</a></aside></div>}
  </section>` })
export class CartComponent {readonly cart=inject(CartService);readonly i18n=inject(I18nService);lineTotal(amount:number,q:number,currency:string){return money(amount*q,currency)}total(){return money(this.cart.total())}}
