import { Injectable, inject } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

import { storefrontConfig } from '../storefront.config';

/**
 * The closed set of things the storefront reports. Matches the API's
 * vocabulary; anything else is refused with a 422.
 */
export type StorefrontEventType =
  | 'page_view'
  | 'product_view'
  | 'add_to_cart'
  | 'checkout_started';

interface StorefrontEvent {
  session_id: string;
  event_type: StorefrontEventType;
  path?: string;
  sku?: string;
  order_id?: string;
  occurred_at: string;
}

const SESSION_KEY = 'opentaberna-analytics-session';

/** Events are batched to this size before an eager flush. */
const BATCH_SIZE = 10;

/** Idle time before a partial batch is sent anyway, in milliseconds. */
const FLUSH_DELAY = 3000;

/**
 * Anonymous shopper telemetry.
 *
 * **A port, not a vendor SDK.** Components call `track()` and know nothing
 * about where events go. Swapping the backend is a change to
 * `storefrontConfig`, not a change to any page.
 *
 * No customer id, email or name is sent. The session identifier is
 * `session_id`, generated by `crypto.randomUUID()` and held
 * in `sessionStorage`, so it dies with the tab and never spans a visit. It is
 * not a cookie or `localStorage`. This is not a legal exemption from consent
 * requirements; review those before deploying publicly.
 *
 * **It must never degrade the shop.** Every failure is swallowed. A shop that
 * breaks because its analytics endpoint is down has been made worse by
 * measuring itself, and events are dropped rather than retried — retrying into
 * a queue during an incident turns a quiet failure into a loud one.
 *
 * **Off unless the operator opts in**, via `storefrontConfig.analytics.enabled`.
 */
@Injectable({ providedIn: 'root' })
export class AnalyticsService {
  private readonly router = inject(Router);

  private readonly config = storefrontConfig.analytics;
  private queue: StorefrontEvent[] = [];
  private timer: ReturnType<typeof setTimeout> | null = null;
  private sessionId: string | null = null;

  get enabled(): boolean {
    return this.config.enabled;
  }

  /**
   * Start reporting page views.
   *
   * Called once at bootstrap. Does nothing when disabled, so no listener is
   * attached and no identifier is ever generated on a deployment that has not
   * opted in.
   */
  init(): void {
    if (!this.enabled) {
      return;
    }

    this.router.events
      .pipe(filter((event): event is NavigationEnd => event instanceof NavigationEnd))
      .subscribe((event) => this.track('page_view', { path: event.urlAfterRedirects }));

    // A closing tab is the common case for losing a partial batch, and
    // visibilitychange fires where unload is unreliable (mobile Safari).
    if (typeof document !== 'undefined') {
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'hidden') {
          this.flush(true);
        }
      });
    }
  }

  track(
    type: StorefrontEventType,
    detail: { path?: string; sku?: string; orderId?: string } = {},
  ): void {
    if (!this.enabled) {
      return;
    }

    this.queue.push({
      session_id: this.session(),
      event_type: type,
      // The API strips query strings too, but sending them at all is a
      // needless way to put an email in a request log.
      path: detail.path ? detail.path.split(/[?#]/)[0] : undefined,
      sku: detail.sku,
      order_id: detail.orderId,
      occurred_at: new Date().toISOString(),
    });

    if (this.queue.length >= BATCH_SIZE) {
      this.flush();
      return;
    }

    this.timer ??= setTimeout(() => this.flush(), FLUSH_DELAY);
  }

  /**
   * Send whatever is queued.
   *
   * `beacon` uses `navigator.sendBeacon`, which survives the page going away —
   * the only way a closing tab's events arrive at all. It cannot set headers,
   * so the payload goes as a Blob typed as JSON.
   */
  private flush(beacon = false): void {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
    if (this.queue.length === 0) {
      return;
    }

    const body = JSON.stringify({ events: this.queue });
    this.queue = [];

    try {
      if (beacon && typeof navigator !== 'undefined' && navigator.sendBeacon) {
        navigator.sendBeacon(
          this.config.endpoint,
          new Blob([body], { type: 'application/json' }),
        );
        return;
      }

      void fetch(this.config.endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body,
        keepalive: true,
      }).catch(() => undefined);
    } catch {
      // Deliberately silent. Analytics failing is not the shopper's problem,
      // and there is nothing useful a storefront can do about it.
    }
  }

  /**
   * The per-tab anonymous identifier.
   *
   * Generated lazily, so a deployment with analytics off never creates one.
   */
  private session(): string {
    if (this.sessionId) {
      return this.sessionId;
    }

    try {
      const stored = sessionStorage.getItem(SESSION_KEY);
      if (stored) {
        this.sessionId = stored;
        return stored;
      }
      const created = crypto.randomUUID();
      sessionStorage.setItem(SESSION_KEY, created);
      this.sessionId = created;
      return created;
    } catch {
      // Private browsing can refuse sessionStorage. An in-memory id still
      // groups this page's events, which is better than dropping them.
      this.sessionId ??= crypto.randomUUID();
      return this.sessionId;
    }
  }
}
